import { FlaskConical } from "lucide-react";

import { useModelInfo } from "@/context/ModelInfoContext";

export function DevModeBanner() {
  const { modelInfo } = useModelInfo();

  if (!modelInfo) return null;

  if (!modelInfo.available) {
    return (
      <div className="no-print flex items-center gap-2 bg-danger-50 px-6 py-2 text-sm text-danger-700">
        <FlaskConical className="size-4 shrink-0" aria-hidden="true" />
        <span>
          No prediction model is loaded. Screening cannot be run until an administrator installs a
          trained model artifact.
        </span>
      </div>
    );
  }

  if (modelInfo.mode === "mock") {
    return (
      <div className="no-print flex items-center gap-2 bg-warning-50 px-6 py-2 text-sm text-warning-600">
        <FlaskConical className="size-4 shrink-0" aria-hidden="true" />
        <span>
          Development mode: predictions are generated by a placeholder model for workflow testing
          only and are not real nutrition-screening results.
        </span>
      </div>
    );
  }

  return null;
}
